[buildPlans.iosevka-serif]
family = "Iosevka Serif"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = false

[buildPlans.iosevka-serif.variants.design]
capital-a = "straight-tri-serifed"
capital-b = "more-asymmetric-bilateral-serifed"
capital-c = "bilateral-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-serifed-capped"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "serifed-symmetric"
capital-k = "curly-serifed"
capital-l = "serifed"
capital-m = "slanted-sides-hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "standing"
capital-s = "bilateral-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "straight-serifed-with-horizontal-crossbar"
c = "bilateral-serifed"
d = "toothed-top-serifed"
e = "flat-crossbar"
f = "flat-hook-serifed"
g = "double-storey"
h = "tailed"
i = "serifed"
j = "flat-hook-serifed"
k = "cursive-serifed"
l = "serifed"
m = "short-leg"
n = "straight"
p = "eared"
q = "straight"
r = "corner-hooked-serifed"
s = "bilateral-serifed"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight"
x = "curly-serifed"
y = "curly-turn"
z = "straight-serifed-with-horizontal-crossbar"
one = "base"
two = "curly-neck"
three = "flattop"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "straight-crossbar-serifed"
eight = "two-circles"
nine = "closed-contour"
tilde = "low"
asterisk = "hex-low"
underscore = "high"
caret = "high"
paren = "flat-arc"
brace = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "square"

[buildPlans.iosevka-serif.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-serif.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-serif.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-serif.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-serif.widths.normal]
shape = 600
menu = 5
css = "normal"
